print "----INTECT tamvans----"
print "Jomblo mavans:v"
print "idaman para wanita javans:v"
print "--napa?gak suka?--"
print "kuy gelud!!!"
print "umur = 15 tahun"
print "kelas= IX Smp"
print "team = W3LL SQUAD"
print "intect gans,yang baca buriq"
